library(Seurat)
library(tidyverse)
library(SeuratWrappers)
options(future.globals.maxSize = 1e9)
library(sceasy)
library(reticulate)
library(anndata)
library(ggplot2)
View(maartenutils::gen_file_overview("SeuratObjects"))
save.dir <- "SeuratObjects"
load("SeuratObjects/2024-03-27-11-14combined_seurat_filter_combinedN6_reselute_clusters_slm_annotated.RData")
library("Nebulosa")
ls()
p1  <- plot_density(combined_seurat_filter, "Slc22a17")
p1 + labs(x = "tsne1", y = "tsne2")
